POST http://localhost:5000/signup
Content-Type: application/json


{
    "username": "utente2",
    "password": "pass2paseojfiefei"
}



###


POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "utente2",
    "password": "foefemmk"
}